# zprofile : 用zsh登陆时加载此文件, 即 login shell

# 加载环境变量,在zshenv中配置了,会自动加载,这里重复配置保险一点
export __PATH_MY_CNF="$HOME/Data/Config"    # 我自己的配置文件目录
export __PATH_MY_SOFT="$HOME/Data/Software" # 我自己的软件目录
export __PATH_HOME_CONFIG="$HOME/.config"   # 默认配置目录

# 加载初始化配置
source "${__PATH_MY_CNF}/zsh/init.sh"
